name: codequantum
description: "HomePage for CODEQUANTUM.IN"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  http: ^1.3.0  
  typewritertext: ^3.0.9
  flutter_flip_card: ^0.0.6
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rainbow_edge_lighting: ^1.0.9
flutter:
  uses-material-design: true
  fonts:
    - family: Roboto_Mono
      fonts: 
        - asset: fonts/RobotoMono-VariableFont_wght.ttf
  assets:
      - assets/CodeQuLog.png
